name: Run tests

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
      - name: Run unit tests
        run: xcodebuild test -project "${GITHUB_WORKSPACE}/OpenBandCyclist/OpenBandCyclist.xcodeproj" -scheme "OpenBandCyclistValidationTests" -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' -derivedDataPath DerivedData
      - name: Upload test logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: UnitTestResults
          path: DerivedData/Logs/Test
